apiVersion: v1
kind: Service
metadata:
  name: userinservice
spec:
  # type: NodePort
  ports: 
    - port: 8083
      # targetPort: 8083
      # nodePort: 30006
  selector:
    name: userms-pod 
    app: pizzashop
